services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  supervisor.manager:
    class: YZ\SupervisorBundle\Manager\SupervisorManager
    arguments: ['%supervisor.servers%']
    public: true